name: Auto Deploy and Merge

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test-deploy-merge:
    name: Test, Deploy, and Merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm globally
        run: |
          npm install -g pnpm
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
        shell: bash
          
      - name: Verify pnpm installation
        run: |
          which pnpm
          pnpm --version
        shell: bash
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash
        
      - name: Lint
        run: pnpm lint
        shell: bash
        
      - name: Type check
        run: pnpm tsc --noEmit
        shell: bash
        
      - name: Run tests
        run: pnpm test
        shell: bash
        
      # Deploy to preview environment
      - name: Deploy to Vercel (Preview)
        id: deploy-preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
      
      # Create and auto-approve PR
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR from ${{ github.ref_name }}"
          title: "Auto PR: ${{ github.ref_name }} → main"
          body: |
            This PR was automatically created by the CI/CD pipeline.
            
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Preview URL: ${{ steps.deploy-preview.outputs.preview-url }}
            
            This branch has passed all tests and was deployed successfully.
          branch: ${{ github.ref_name }}
          base: main
      
      - name: Enable Pull Request Auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run: |
          gh pr merge --auto --squash "${{ steps.create-pr.outputs.pull-request-number }}"
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 